Надо подкачаться
htmlacademy-javascript/940469-keksobooking-23 pull request #10
Opened 2021-07-05 12:00 UTC by cat3a

2021-07-05 16:44 UTC, balesniy requested changes
с загрузкой данных все хорошо, что нужно поправить:
- разгрузить модуль map - вынести работу с формой и сообщениями
- поправить установку-снятие обработчиков

2021-07-05 16:44 UTC, balesniy commented on js/map.js
> +document.addEventListener('keydown', (evt) => {
посмотри на критерий https://up.htmlacademy.ru/javascript/23/criteries#b26 - нам нужно установить обработчики при открытии окна, и снять при закрытии, для этого их нужно сохранить в переменную (анонимный не снять). и не забыть по клику снять обработчик keydown и наоборот

2021-07-05 16:44 UTC, balesniy commented on js/map.js
> +  if (evt.keyCode === 27) {
код нужно оформить в константу или использовать https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code

2021-07-05 16:44 UTC, balesniy commented on js/map.js
> +    removeMessage(errorMessageShow, successMessageShow);
в successMessageShow будет новый клонированный элемент, а нам нужен актуальный со страницы

2021-07-05 16:44 UTC, balesniy commented on js/map.js
> +  const errorMessage = document.querySelector('#error');
повторяется код обработчиков, его можно оформить в функцию

2021-07-05 16:44 UTC, balesniy commented on js/map.js
> +const addressInput = document.querySelector('#address');
код заполнения поля формы можно перенести в модуль формы

2021-07-05 16:44 UTC, balesniy commented on js/map.js
> +sendForm.addEventListener('submit', (evt) => {
этот код относится к работе с формой

2021-07-05 18:08 UTC, cat3a commented on js/map.js
> +document.addEventListener('keydown', (evt) => {
@balesniy, спасибо большущее за проверку задания! :smile:  В модуле map, да, там как - то сейчас не очень хорошо все, мягко говоря. Честно говоря, там  какой-то бардак, признаю. :-1:

2021-07-05 18:15 UTC, cat3a commented on js/map.js
> +  if (evt.keyCode === 27) {
@balesniy, о спасибо за дополнительные материалы! Посижу почитаю. :+1:

2021-07-05 18:30 UTC, cat3a commented on js/map.js
> +    removeMessage(errorMessageShow, successMessageShow);
@balesniy, хмм, что-то я не знаю зачем я это сделала (клонировала его еще раз). :thinking:  Просто я долго с этими сообщениями провозилась. Я сначала их сделала в произвольной форме, а потом ТЗ прочитала, "обрадовалась"  :fearful: , что все нужно переделать и спешно все переделала.  Это я зря как-то.

2021-07-05 18:38 UTC, cat3a commented on js/map.js
> +const addressInput = document.querySelector('#address');
@balesniy, согласна. У меня тут с модулями какие-то проблемы странные, я похоже не до конца понимаю, как это работает... Если я экспортирую и импортирую например так: export из map в form, а потом наоборот из form в map (при этом функции и константы у меня разные, не одни и те же), то у меня ничего не работает. Почему так получается и как этого избежать?

2021-07-05 19:27 UTC, balesniy commented on js/map.js
> +const addressInput = document.querySelector('#address');
стандартное решение - экспортировать функции, а не значения, но лучше конкретный пример разобрать

2021-07-05 21:22 UTC, cat3a commented on js/map.js
> +const addressInput = document.querySelector('#address');
@balesniy, да, согласна, что без реальных примеров сложно такое обсуждать.

2021-07-06 17:05 UTC, cat3a commented on js/map.js
> +const addressInput = document.querySelector('#address');
@balesniy, разобралась в чем дело, и почему такие ошибки возникают. Там порядок импорта модулей в main.js был виноват.

2021-07-06 20:00 UTC, balesniy approved these changes
обработчики теперь в порядке, но остались всякие мелочи, посмотри и поправь пожалуйста

2021-07-06 20:00 UTC, balesniy commented on js/form.js
> +  if (document.body.contains(error)) {
error ищется в документе, можно не проверять contains, достаточно проверить null

2021-07-06 20:00 UTC, balesniy commented on js/form.js
> +  document.addEventListener('click', clickId = () => {
посмотри на критерий https://up.htmlacademy.ru/javascript/23/criteries#d27

2021-07-06 20:00 UTC, balesniy commented on js/form.js
> +    removeMessage(successMessage, errorMessage);
функция removeMessage не принимает аргументы

2021-07-06 20:00 UTC, balesniy commented on js/form.js
> +    if (evt.keyCode === 27) {
27 нужно оформить в константу

2021-07-06 20:00 UTC, balesniy commented on js/form.js
> +  document.addEventListener('keydown', keydownId = (evt) => {
обработчики просят назвать по схеме, см пример в https://up.htmlacademy.ru/javascript/23/criteries#d4

2021-07-06 20:00 UTC, balesniy commented on js/form.js
> +const fetchData = createFetch(
этот код скорее относится к карте, чем к форме

2021-07-06 20:00 UTC, balesniy commented on js/map.js
> +  addressInput.value = `${Number(CENTER_TOKIO_LATITUDE).toFixed(5)}, ${Number(CENTER_TOKIO_LONGITUDE).toFixed(5)}`;
повторяется код установки значения в поле адреса, просится в функцию

2021-07-06 20:00 UTC, merged

2021-07-06 20:32 UTC, cat3a commented on js/form.js
> +  document.addEventListener('click', clickId = () => {
@balesniy, как всегда, спасибо огромное за проверку домашнего задания! 
Жаль, я долго думала, как эти обработчики удалить. :disappointed:  Ладно, подумаю значит еще.