Module12 task1
htmlacademy-javascript/940469-keksobooking-23 pull request #11
Opened 2021-07-08 14:28 UTC by cat3a

2021-07-11 21:18 UTC, balesniy requested changes
- с фильтрами отлично получилось, нужно доработать форму - сбрасывать фильтры при сбросе формы, и скрывать открытый балун
- "поплыли" названия функций, посмотри еще раз критерии пожалуйста, это или "глагол, отражающий действие" или обработчик - и тогда по схеме "элемент+событие"

2021-07-11 21:18 UTC, balesniy commented on js/filters.js
> +  changeFormHandler(similarObject);
тут скорее setFormHandler, обработчик не меняется

2021-07-11 21:18 UTC, balesniy commented on js/filters.js
> +  filterForm.addEventListener('change', createNewTickets(similarObject));
массивы просят называть во множественном числе, чтобы не путать их с объектами

2021-07-11 21:18 UTC, balesniy commented on js/filters.js
> +const createNewTickets = (similarObject) => debounce(() => {
функция не создает объекты, она возвращает обработчик, точнее будет ее назвать например getFilterHandler

2021-07-11 21:18 UTC, balesniy commented on js/form.js
> +mapEnableHandler('ad-form--disabled', true);
такое название подходит для обработчиков, тут обычная функция - нужен глагол

2021-07-11 21:18 UTC, balesniy commented on js/form.js
> +    if (evt.keyCode === ESCAPE_CODE || evt.type === 'click') {
https://up.htmlacademy.ru/javascript/23/criteries#d24

2021-07-11 21:18 UTC, balesniy commented on js/form.js
> +  const closePopupListener = () => {
нужно уточнить название

2021-07-11 21:18 UTC, balesniy commented on js/map.js
>    addressInput.value = (`${Number(evt.target.getLatLng().lat).toFixed(5)}, ${Number(evt.target.getLatLng().lng).toFixed(5)}`);
повторяет setAddress

2021-07-11 21:18 UTC, balesniy commented on js/server-data.js
> +  const errorMessage = document.querySelector('#error');
поиск шаблонов можно вынести из функции, https://up.htmlacademy.ru/javascript/23/criteries#d21

2021-07-12 09:46 UTC, cat3a commented on js/filters.js
> +const HOUSE_PRICE_RANGE = {
@balesniy, огромное спасибо за проверку задания! :smile:

2021-07-12 10:03 UTC, cat3a commented on js/filters.js
> +  (similarObjectsFiltered.slice(0, SIMILAR_OBJECT_COUNT).forEach((similarObjectFiltered) => createMarker(similarObjectFiltered)));
@balesniy, я пока так оставила бы. Попросят, значит переделаю. :smile:

2021-07-12 16:10 UTC, cat3a commented on js/filters.js
> +const HOUSE_PRICE_RANGE = {
@balesniy, а HOUSE_PRICE_RANGE - это перечисление или  объект все-таки? У меня почему - то трудности с тем, как объект  от перечисления  отличить. :thinking:

2021-07-12 16:20 UTC, balesniy commented on js/filters.js
> +const HOUSE_PRICE_RANGE = {
тут у вас критерий просит однородные константы оформить особым образом, а вообще классический пример перечисления - карточные масти, это закрытый набор значений, причем сами значения не важны, главное их отличие, см https://ru.wikipedia.org/wiki/Перечисляемый_тип

2021-07-12 16:47 UTC, cat3a commented on js/filters.js
> +const HOUSE_PRICE_RANGE = {
@balesniy, огромное спасибо! Поняла в чем дело. :smile:

2021-07-13 10:41 UTC, balesniy requested changes
- часть замечаний осталась с прошлого ревью, возможно не приехали изменения в ПР
- все еще сохраняется проблема с названиями функций, в них стало легко запутаться, потому что названия перестали соответствовать действию, посмотри еще раз на них пожалуйста, спрашивай если сомневаешься

2021-07-13 10:41 UTC, balesniy commented on js/filters.js
> +    if (typeof offer.features !== 'undefined') {
тут надежнее проверять на isArray

2021-07-13 10:41 UTC, balesniy commented on js/form.js
> +  document.removeEventListener('keydown', messageKeyCodeHandler);
обработчики просят назвать по схеме "элемент+событие", тут у нас нажатие клавиши на документе, получается documentKeydownHandler

2021-07-13 10:41 UTC, balesniy commented on js/form.js
> +  const closeMessage = () => {
функции нужно дать более наглядное название, соответствующее ее действию, она не закрывает сообщение, а устанавливает обработчики, похоже тут document.addEventListener перепутан с document.removeEventListener

2021-07-13 10:41 UTC, balesniy commented on js/form.js
> +const enableMap = (selector = 'ad-form--disabled', isDisabled = false) => {
функция не активирует карту, она активирует форму

2021-07-13 10:41 UTC, balesniy commented on js/server-data.js
> +  const errorMessage = document.querySelector('#error');
все еще актуально

2021-07-13 13:40 UTC, cat3a commented on js/filters.js
> +    if (typeof offer.features !== 'undefined') {
@balesniy, как всегда, огромное спасибо за проверку домашнего задания!

2021-07-13 13:46 UTC, cat3a commented on js/form.js
> +  document.removeEventListener('keydown', messageKeyCodeHandler);
@balesniy, я когда называла, решила почему-то что document, - слишком пространно и не очень понятно что этот и где, поэтому конкретизировала до message. Но раз нужно document, то пусть будет document.

2021-07-13 13:54 UTC, cat3a commented on js/form.js
> +const enableMap = (selector = 'ad-form--disabled', isDisabled = false) => {
@balesniy, согласна, map не особо к месту тут. Я когда писала, думала про то, что у меня теперь есть форма собственно форма (для отправки, основная часть) и форма на карте для фильтрации. Можно ее назвать enableMapFilter тогда?

2021-07-13 13:56 UTC, balesniy commented on js/form.js
> +const enableMap = (selector = 'ad-form--disabled', isDisabled = false) => {
да, тут главное чтобы тебе через полгода было сразу понятно, что эта функция делает

2021-07-13 13:59 UTC, cat3a commented on js/server-data.js
> +  const errorMessage = document.querySelector('#error');
@balesniy, хм, вот это я дала маху, честно говоря. -1 Прошу прощения, у меня просто все правки на листочке выписаны были и эту я случайно пропустила. :confused:

2021-07-13 14:08 UTC, cat3a commented on js/form.js
> +const enableMap = (selector = 'ad-form--disabled', isDisabled = false) => {
@balesniy, ну, я думаю, мне будет понятно. А еще, наверное, будет немного весело и стыдно, глядя на такой код. :smile: Я надеюсь, через пол года, я уже  лучше кодить буду.

2021-07-13 15:08 UTC, balesniy commented on js/form.js
> +const enableMap = (selector = 'ad-form--disabled', isDisabled = false) => {
код в порядке, сейчас проблема исключительно в нейминге. попробуй "прочитать" свой код не заглядывая в тело функций, должно быть однозначно понятно что именно происходит глядя на имена функций

2021-07-13 15:11 UTC, balesniy commented on js/form.js
> +const enableMap = (selector = 'ad-form--disabled', isDisabled = false) => {
"ну, я думаю, мне будет понятно." хорошо если так, я по опыту предвижу трудности с конструкцией 
```
map.on('load', () => {
     enableMap();
   });
```
скорее всего придется открывать соседний модуль и смотреть что же именно там присходит при загрузке карты

2021-07-13 20:53 UTC, cat3a commented on js/form.js
> +const enableMap = (selector = 'ad-form--disabled', isDisabled = false) => {
@balesniy, ну, да, согласна, конкретно для этой функции,  это не очень удачное название. А так, зная себя, я могу сказать, что я все равно в код полезу и буду смотреть, что делает эта функция, еще забэкаплю ее 10 раз перед изменением/удалением, а то мало ли... :smile:

2021-07-14 08:56 UTC, balesniy requested changes

2021-07-14 08:56 UTC, balesniy commented on js/filters.js
> +  if (houseRoomsFilter.value === SPECIAL_VALUE || houseRoomsFilter.value === `${offer.rooms}`) {
https://up.htmlacademy.ru/javascript/23/criteries#d18

2021-07-14 08:56 UTC, balesniy commented on js/filters.js
> +  if (houseGuestsFilter.value === SPECIAL_VALUE || houseGuestsFilter.value === `${offer.guests}`) {
https://up.htmlacademy.ru/javascript/23/criteries#d18

2021-07-14 08:56 UTC, balesniy commented on js/filters.js
> +const isSelectedFeatures = (similarObjects) => {
в параметре один объект или коллекция?

2021-07-14 08:56 UTC, balesniy commented on js/filters.js
> +const filterSimilarObjects = (similarObjects) => isSelectedHouseType(similarObjects) && isSelectedPrice(similarObjects) && isSelectedRooms(similarObjects) && isSelectedGuests(similarObjects) && isSel
функция проверяет один объект или всю коллекцию?

2021-07-14 08:56 UTC, balesniy commented on js/filters.js
> +const createNewTickets = (similarObjects) => debounce(() => {
функция обрабатывает один объект или всю коллекцию?

2021-07-14 08:56 UTC, balesniy commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
message находится в области видимости, можно его удалять, а так "всплепую" удаляется произвольный узел из body

2021-07-14 08:56 UTC, balesniy commented on js/server-data.js
> +    .then(enableForm)
посмотри на https://up.htmlacademy.ru/javascript/23/project/keksobooking#keksobooking-1-2  и https://up.htmlacademy.ru/javascript/23/project/keksobooking#keksobooking-5-10 - форму объявления мы активируем при загрузке карты, а при загрузке списка - форму фильтров

2021-07-14 11:15 UTC, cat3a commented on js/filters.js
> +  if (houseRoomsFilter.value === SPECIAL_VALUE || houseRoomsFilter.value === `${offer.rooms}`) {
@balesniy, как всегда большое спасибо за проверку!

2021-07-14 11:16 UTC, cat3a commented on js/filters.js
> +const isSelectedFeatures = (similarObjects) => {
@balesniy, так туда вроде сразу весь массив приходит или нет? Что-то я уже запуталась.

2021-07-14 11:28 UTC, cat3a commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
@balesniy, почему произвольный? Последний из созданных.  Вероятность, что у нас за промежуток времени, когда попап появился и пользователь его закрыл что - то еще появится на последнем месте в body конечно не ноль, но почти ноль. Вот я и решила, что можно так сделать. А как там вообще можно message правильно найти тогда?

2021-07-14 11:31 UTC, cat3a commented on js/server-data.js
> +    .then(enableForm)
@balesniy, поправила. Я когда их разделяла и переназывала, я их местами перепутала. :disappointed:

2021-07-14 12:32 UTC, balesniy commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
он у тебя уже есть в переменной message, его не надо искать, так же как на страницу его добавляли, его можно и удалить

2021-07-14 12:32 UTC, balesniy commented on js/server-data.js
> +    .then(enableForm)
вот для этого и нужны хорошие названия

2021-07-14 13:20 UTC, cat3a commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
@balesniy, не могу так удалить, в том-то и дело. Uncaught TypeError: Cannot read property 'removeChild' of null
    at HTMLDocument.documentClickHandler (form.js:35).  Вставлено через: document.body.appendChild(message.content); Что я делаю не так?

2021-07-14 14:02 UTC, balesniy commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
мне нужно посмотреть как именно ты удаляешь, судя по ошибке, метод вызывается у пустого элемента. вот как то так можно сделать - https://codepen.io/balesniy/pen/yLbgGEg?editors=1010

2021-07-14 14:20 UTC, cat3a commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
@balesniy, хорошо. Какой конкретно критерий я нарушаю удаляя элемент через document.body.removeChild(document.body.children[document.body.children.length - 1]); ?

2021-07-14 14:36 UTC, cat3a commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
@balesniy, добавляю также как удаляю поиск по id => клонирование узла =>  добавление через  document.body.appendChild(message.content) => удаление через document.body.removeChild(message.content) или document.body.removeChild(message).

2021-07-14 15:01 UTC, balesniy commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
конкретно критерии не нарушаешь. в message.content лежит fragment, после вставки содержимого на страницу он пустой и его не удалить. посмотри еще раз мой пример, сам шаблон копировать не надо, у него в свойстве content лежит fragment, который оборачивает содержимое шаблона

2021-07-14 16:21 UTC, cat3a commented on js/form.js
> +    document.body.removeChild(document.body.children[document.body.children.length - 1]);
@balesniy, да это я уже поняла, что он пустой.  Спасибо за образец! Переделала по нему.  Так просто длинно получается.

2021-07-14 16:27 UTC, cat3a commented on js/filters.js
> +const isSelectedFeatures = (similarObjects) => {
@balesniy, хм, дело в названии функции или в названии того, что приходит в нее?

2021-07-14 16:36 UTC, balesniy commented on js/filters.js
> +const isSelectedFeatures = (similarObjects) => {
в названии параметра

2021-07-14 17:06 UTC, cat3a commented on js/filters.js
> +const isSelectedFeatures = (similarObjects) => {
@balesniy, можно я назову его it ?

2021-07-14 18:44 UTC, merged