Правда или действие (часть 1)
htmlacademy-javascript/940469-keksobooking-23 pull request #7
Opened 2021-06-20 13:16 UTC by cat3a

2021-06-20 18:52 UTC, balesniy requested changes
с валидацией все отлично! попробуй сделать restrictSelect универсальной и упростить getRoom, если засомневаешься, пиши, я намекну на возможное решение )

2021-06-20 18:52 UTC, balesniy commented on index.html
> +        <form class="map__filters" method="post" enctype="multipart/form-data" action="https://23.javascript.pages.academy/keksobooking" autocomplete="off">
отправлять мы будет форму ad-form, нужно ей указать action

2021-06-20 18:52 UTC, balesniy commented on js/form.js
> +const  disableForm = (selector='ad-form--disabled', token='disabled', boolean= false) => {
параметру boolean нужно дать более наглядное имя, и передать его в classList.toggle как в fieldset.toggleAttribute

2021-06-20 18:52 UTC, balesniy commented on js/utils.js
> +  Array.from(collection).forEach((collectionItem) => collectionItem.setAttribute('disabled', 'disabled'));
у дом элементов можно обращаться к свойствам вместо атрибутов, `collectionItem.disabled = true`

2021-06-20 18:52 UTC, balesniy commented on js/utils.js
> +  for (const collectionItem of collection) {
цикл повторяет forEach

2021-06-20 18:52 UTC, balesniy commented on js/utils.js
> +//TODO: 3 идущие далее функции, вероятно, потом станут одной, но я пока не знаю, как корректно передать условие.
несколько условий [conditionOne, и др] можно передать массивом и проверять совпадение методом some или includes

2021-06-20 18:52 UTC, balesniy commented on js/utils.js
> +    if (collectionItem.textContent === condition) {
textContent довольно хрупкая штука, можно взять value если это option

2021-06-20 18:52 UTC, balesniy commented on js/restrictions.js
> +roomInput.addEventListener('change', getRoom);
обработчики событий просят особого нейминга, посмотри примеры в https://up.htmlacademy.ru/javascript/23/criteries#d4

2021-06-20 18:52 UTC, balesniy commented on js/restrictions.js
> +  if (evt.target.value === '1') {
такие похожие проверки удобно оформить в объект-справочник, вида `{'2': ['для 1 гостя','для 2 гостей']}` если нужно уточнить значение по-умолчанию, то его тоже записать в отдельное поле. тогда функция получится лаконичной, а данные всегда проще править чем код

2021-06-20 18:52 UTC, balesniy commented on js/utils.js
> +      if (isSelect) {
про параметр isSelect я не понял идею, тут просится параметр по-умолчанию, который будет установлен при смене значения, но не может быть boolean

2021-06-20 20:06 UTC, cat3a commented on index.html
> +        <form class="map__filters" method="post" enctype="multipart/form-data" action="https://23.javascript.pages.academy/keksobooking" autocomplete="off">
@balesniy , огромное спасибо за проверку задания! Да, что-то с формой я напортачила.  :thinking:  И почему я решила, что она на странице одна и влепила первой попавшейся атрибуты?! Честно обещаю быть внимательнее в дальнейшем. И главное, ведь попробовала отправить, она нормально не отправилась, но я почему-то решила, что так и должно быть,  что мы ее позже доработаем.

2021-06-20 20:15 UTC, cat3a commented on js/utils.js
> +//TODO: 3 идущие далее функции, вероятно, потом станут одной, но я пока не знаю, как корректно передать условие.
@balesniy, спасибо большое за совет! Передать - то я их массивом пробовала, а вот распарсить массив в условия нормально у меня не получилось пока почему-то.  Нужно будет попробовать еще раз через includes или some.

2021-06-20 20:27 UTC, cat3a commented on js/utils.js
> +      if (isSelect) {
@balesniy, этот параметр задумывался как параметр для вариативной установки selected. Т.е. если он === true , то мне  нужен selected, а если === false, мне он не нужен.  Не знаю правильно так или нет, но хотелось как - то так и вроде бы работает.

2021-06-20 20:32 UTC, balesniy commented on js/utils.js
> +      if (isSelect) {
работает, устанавливает всем доступным, можно уточнить поведение, устанавливать только на заданный по-умолчанию, например по индексу или значению, у селектов есть отдельные свойства для доступа к опциям, https://learn.javascript.ru/form-elements#select-i-option

2021-06-20 20:45 UTC, cat3a commented on js/utils.js
> +      if (isSelect) {
@balesniy, да похоже на то. :smile:  Посмотрела сейчас уже повнимательнее,  у 100 комнат, обнаружила 2 selected... Нужно будет исправить. Спасибо за ссылку!

2021-06-21 18:54 UTC, merged

2021-06-21 20:26 UTC, cat3a commented on index.html
> +            <option value="12:00" selected>После 12</option>st
@balesniy, большущее спасибо за проверку домашнего задания! Да, st тут как-то не особо к месту... Странно, котейка, вроде, по клавиатуре  не ходил. :thinking:

2021-06-21 20:33 UTC, cat3a commented on js/utils.js
> +  const collection = collectionParent.children;
@balesniy, да пока одно на другое меняла, о том, что переназвать нужно забыла. Спасибо!