Правда или действие (часть 2)
htmlacademy-javascript/940469-keksobooking-23 pull request #8
Opened 2021-06-23 22:52 UTC by cat3a

2021-06-24 20:55 UTC, balesniy requested changes
интересные решения, видно что с js тебе нравится играть) теперь их нужно упростить до банальности

2021-06-24 20:55 UTC, balesniy commented on js/form.js
> +/*TODO: Я пока все-таки оставлю на самих формах добавление/снятие класса, так как исходя из ТЗ сильно напрашивается. Меня смущает:
👍

2021-06-24 20:55 UTC, balesniy commented on js/restrictions.js
> +  if (evt.target.value === ROOMS['for 1 guest']['checked']) {
каскад условий можно удобно заменить на получение значения из ROOMS по ключу, там у тебя готовый справочник, ключ получаем из объекта события, останется одна строчка кода, типа ROOMS[evt.target.value] если не получится, пиши, я подскажу

2021-06-24 20:55 UTC, balesniy commented on js/restrictions.js
> +addEventListener('change', roomChangeHandler);
нужно указать, на какой элемент добавляем обработчик

2021-06-24 20:55 UTC, balesniy commented on js/restrictions.js
> +  for (let i = 0; i <= houseTypes.length; i++) {
тут тоже цикл лишний, у нас в справочнике есть готовое значение, остается его получить по ключу и применить в поле, этот паттерн часто в формах используется, нам нужно его освоить

2021-06-24 20:55 UTC, balesniy commented on js/restrictions.js
> +addEventListener('change', houseChangeHandler);
без указания элемента получаем глобальный обработчик

2021-06-24 20:55 UTC, balesniy commented on js/restrictions.js
> +const  inputListenHandler = (getPriceItem) => () => {
функция вернёт анонимный обработчик, его будет не снять с элемента

2021-06-24 20:55 UTC, balesniy commented on js/utils.js
> +
возможно стоит созвониться - проговорить, у меня есть старый пример, еще на es5, у тебя получится лаконичнее, но принцип решения можно взять - https://codepen.io/balesniy/pen/EoVRzg?editors=0010

2021-06-24 20:55 UTC, balesniy commented on js/utils.js
> +const timeChangeHandler = (selectItems, linkedItems) => (evt) => {
нам нужно согласовать значения в инпутах , достаточно  input1.value = input2.value

2021-06-25 10:30 UTC, cat3a commented on js/form.js
> +/*TODO: Я пока все-таки оставлю на самих формах добавление/снятие класса, так как исходя из ТЗ сильно напрашивается. Меня смущает:
@balesniy, как всегда большущее спасибо за проверку задания! 
 Упростить решения до банальности, конечно можно, но проблема в том, что я себе пока плохо представляю как должна выглядеть эта банальность. :thinking:  Мало опыта еще пока для этого.  :smiley:

2021-06-25 10:40 UTC, cat3a commented on js/restrictions.js
> +addEventListener('change', roomChangeHandler);
@balesniy, просто называть его selectChangeHandler  мне как-то не хочется, он там не один такой обработчик на select, да и суть это мало отражает(селектов-то там много же).

2021-06-25 10:43 UTC, cat3a commented on js/restrictions.js
> +addEventListener('change', houseChangeHandler);
@balesniy, согласна. Здесь та же беда, что и с предыдущим элементом select. Но по критериям, да не положено так называть.

2021-06-25 10:43 UTC, balesniy commented on js/restrictions.js
> +addEventListener('change', roomChangeHandler);
_element_. addEventListener

2021-06-25 10:54 UTC, cat3a commented on js/utils.js
> +
@balesniy, спасибо большое за пример! Если честно, я не очень хочу тут метод .setCustomValidity() там использовать. Просто всегда найдутся пользователи, которые все равно будут пытаться выбрать активный элемент списка. Легче сразу не давать выбрать элемент, заблокировав его. Нет активного элемента  - нет проблемы! :smiley:

2021-06-25 10:55 UTC, balesniy commented on js/utils.js
> +
можно не использовать, там оба варианта есть

2021-06-25 11:29 UTC, cat3a commented on js/restrictions.js
> +addEventListener('change', roomChangeHandler);
@balesniy, поняла, спасибо! Что-то я туплю. Может из-за жары?! :smile: Так-то да, вообще-то, без элемента  уже глобальный обработчик событий получается. :confused:

2021-06-27 17:53 UTC, cat3a commented on js/utils.js
> +
@balesniy, если честно, я не понимаю, чем такое решение лучше.  В чем его преимущество? Зачем там столько переменных, объектов, и функций каких - то заведено? :fearful:  Может я лучше что-то другое "изобрету",  на основе своего решения, если пойму в чем проблема?

2021-06-27 18:56 UTC, balesniy commented on js/utils.js
> +
преимущество в отсутствии лишней логики, мы декларативно описываем в данных допустимые значения, и дальше "применяем данные" на поле, там все решение получается в одну строчку, "включи все разрешенные", без вложенных условий

2021-06-28 00:16 UTC, cat3a commented on js/utils.js
> +
@balesniy, кажется дошло! Большое спасибо! По крайней мере, от условий я избавилась совсем.

2021-06-28 10:28 UTC, balesniy approved these changes

2021-06-28 10:28 UTC, balesniy commented on js/utils.js
> +    collectionItem.enabled = conditions.includes(Number(collectionItem.value));
это лишнее

2021-06-28 10:28 UTC, balesniy commented on js/utils.js
> +    collectionItem.selected = !(collectionItem.disabled + conditions.length - 1);
- тут происходит неявное приведение типов, сложение булевого с числом. 
- чтобы установить значение на поле, достаточно записать его один раз, вне цикла.
- в данных есть явное поле checked, лучше его и устанавливать, без вычислений

2021-06-28 10:28 UTC, merged

2021-06-28 14:24 UTC, cat3a commented on js/utils.js
> +    collectionItem.selected = !(collectionItem.disabled + conditions.length - 1);
@balesniy, спасибо огромное за проверку задания и рекомендации! :smile:  Нужно будет попробовать так сделать!