Помощь друга
htmlacademy-javascript/940469-keksobooking-23 pull request #9
Opened 2021-06-29 23:26 UTC by cat3a

2021-06-30 20:55 UTC, balesniy requested changes
с картой хорошо получилось, отметил пару мелочей поправить

2021-06-30 20:55 UTC, balesniy commented on index.html
> +      <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
скрипты нужно подключить единообразно, вне основной разметки, это может быть head или как main, перед закрывающим body

2021-06-30 20:55 UTC, balesniy commented on js/generation-data.js
> +  for (let i = 0; i <= similarObjects.length - 1; i++) {
посмотри на критерий https://up.htmlacademy.ru/javascript/23/criteries#d26 - тут хорошо подойдет map

2021-06-30 20:55 UTC, balesniy commented on js/generation-data.js
> +  return similarFragment;
фрагмент нам уже не нужен, можно вернуть массив с элементами

2021-06-30 20:55 UTC, balesniy commented on js/marks.js
> +    lat: 35.675,
центр города нужно оформить в константы, чтобы без магии

2021-06-30 20:55 UTC, balesniy commented on js/marks.js
> +const addressInput = document.querySelector('#address');
код работы с формой лучше вынести в модуль формы

2021-06-30 20:55 UTC, balesniy commented on js/marks.js
> +  item++;
лучше передавать в функцию нужный элемент параметром, иначе функция вынуждена знать про устройство массива

2021-06-30 20:55 UTC, balesniy commented on js/marks.js
> +  addressInput.value = `${evt.target.getLatLng()}`.slice(7, -1).split(',').map((coordinate) => (Number(coordinate).toFixed(5))).join(', ');
посмотри на evt.target.getLatLng

2021-06-30 21:07 UTC, cat3a commented on index.html
> +      <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
@balesniy,  да, это я зря. Это называется, когда копируешь из демонстрации, хорошо подумай, все ли ты делаешь правильно.

2021-06-30 21:11 UTC, cat3a commented on js/generation-data.js
> +  return similarFragment;
@balesniy, я сначала попыталась вернуть массив, но у меня там пустые фрагменты почему-то были. :disappointed:  Где-то что-то плохо продумала, решила вернуть прямо сам фрагмент. Нужно будет еще раз попробовать с массивом, раз нужен массив.

2021-06-30 21:20 UTC, cat3a commented on js/marks.js
> +  addressInput.value = `${evt.target.getLatLng()}`.slice(7, -1).split(',').map((coordinate) => (Number(coordinate).toFixed(5))).join(', ');
@balesniy, большое спасибо за проверку д/з, а за  evt.target.getLatLng отдельное спасибо! :smile:

2021-07-01 10:19 UTC, cat3a commented on js/generation-data.js
> +  return similarFragment;
@balesniy, и все-таки я не совсем понимаю, массив чего мне там нужно вернуть, массив фрагментов или чего-то другого?

2021-07-01 10:28 UTC, balesniy commented on js/generation-data.js
> +  return similarFragment;
массив элементов. сейчас функция создает элемент ticket, сохраняет его в массив tickets, потом прикрепляет его к фрагменту, возвращает фрагмент, выбрасывает массив. потом другая функция получает фрагмент, разбирает его в массив элементов, выбрасывает фрагмент. фрагмент в этой цепочке выглядит лишним.

2021-07-01 12:19 UTC, cat3a commented on js/generation-data.js
> +  return similarFragment;
@balesniy, поняла, спасибо! У меня, потом, да: Array.from(getTickets().children).forEach((ticket) => {
  tickets.push(ticket);
});

2021-07-02 06:34 UTC, balesniy approved these changes

2021-07-02 06:34 UTC, balesniy commented on js/leaflet.js
> +similarObjects.forEach((similarObject, item= 0) => {
- forEach передает вторым параметром в колбэк индекс массива, нам не нужно его самостоятельно поддерживать, достаточно объявить
- в createMarker можно не передавать весь массив tickets, достаточно передать один объект
- имеет смысл дать более общее название модулю, например map, чтобы не перепутать его с модулем библиотеки

2021-07-02 06:34 UTC, merged

2021-07-02 08:59 UTC, cat3a commented on js/leaflet.js
> +similarObjects.forEach((similarObject, item= 0) => {
@balesniy, большущее спасибо за проверку задания! 
У item я уберу значение стартовое. Это я просто искала, почему у меня пустой  popup получился.  И, на всякий случай, поставила значение руками. :smile: